alias grep="grep --color=auto"
alias ls="ls --color=auto"

alias e="$EDITOR"
alias g="git"
alias r="rails"
alias ll="l -l"
alias rm="rm -i"
alias ff="nohup firefox > /dev/null"
alias vim="vim -p"
alias sys="systemctl"
alias rss="newsbeuter"
alias pdf="zathura"
alias email="mutt"
alias music="cmus"
alias video="mpv"

alias please="sudo"

hash colordiff 2>/dev/null && alias diff="colordiff"
