#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width           0
bspc config window_gap             0
bspc config split_ratio            0.50
bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config focus_follows_pointer  true

bspc rule -a gimp state=fullscreen follow=on
bspc rule -a mvp state=fullscreen
bspc rule -a Zathura state=tiled
bspc rule -a "firefox":"Navigator" state=tiled
bspc rule -a "firefox":"Firefox" state=floating # downloading dialog
bspc rule -a "firefox":"firefox" state=floating # saving dialog

polybar bspwm &

alacritty &
